//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExcelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntityMaker.Properties.ExcelResources", typeof(ExcelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Logical name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DATA_TYPE {
            get {
                return ResourceManager.GetString("DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DEF {
            get {
                return ResourceManager.GetString("DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Bool (*.xlsx)|*.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXCEL_EXTENSION_FILTER {
            get {
                return ResourceManager.GetString("EXCEL_EXTENSION_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Physical name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LOGICAL_NAME {
            get {
                return ResourceManager.GetString("LOGICAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PHYSICAL_NAME {
            get {
                return ResourceManager.GetString("PHYSICAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED", resourceCulture);
            }
        }
    }
}
