//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntityMaker.Properties.MainWindowResources", typeof(MainWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   After conversion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AFTER_CONVERSION {
            get {
                return ResourceManager.GetString("AFTER_CONVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CAMEL {
            get {
                return ResourceManager.GetString("CAMEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONVERSION_PATTERN {
            get {
                return ResourceManager.GetString("CONVERSION_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONVERSION_SOURCE {
            get {
                return ResourceManager.GetString("CONVERSION_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Definition Excel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DEFINE_EXCEL {
            get {
                return ResourceManager.GetString("DEFINE_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DEFINITION {
            get {
                return ResourceManager.GetString("DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column ID,COLUMN_ID,char(n),Yes
        ///Column name,COLUMN_NAME,nvarchar(n),Y
        ///User password,USER_PASSWORD,text,No
        ///Role ID,ROLE_ID,int,N
        ///Creation date and time,CREATED_AT,date,
        ///updated_date,UPDATED_AT,datetime, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXAMPLE_DEFINITION {
            get {
                return ResourceManager.GetString("EXAMPLE_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COLUMN_ID
        ///COLUMN_NAME
        ///USER_PASSWORD
        ///ROLE_ID
        ///CREATED_AT
        ///UPDATED_AT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXAMPLE_NAME_ONLY {
            get {
                return ResourceManager.GetString("EXAMPLE_NAME_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXCEL {
            get {
                return ResourceManager.GetString("EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get or set {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GET_OR_SET {
            get {
                return ResourceManager.GetString("GET_OR_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lower case letters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LOWER_CASE {
            get {
                return ResourceManager.GetString("LOWER_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M a k e に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MAKE {
            get {
                return ResourceManager.GetString("MAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NAME_ONLY {
            get {
                return ResourceManager.GetString("NAME_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OPEN_FILE {
            get {
                return ResourceManager.GetString("OPEN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pascal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PASCAL {
            get {
                return ResourceManager.GetString("PASCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PASTE_TYPE {
            get {
                return ResourceManager.GetString("PASTE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROPERTY {
            get {
                return ResourceManager.GetString("PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PROPERTY_NAME {
            get {
                return ResourceManager.GetString("PROPERTY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select  file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECT_FILE {
            get {
                return ResourceManager.GetString("SELECT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Snake to Pascal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SNAKE_TO_PASCAL {
            get {
                return ResourceManager.GetString("SNAKE_TO_PASCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stick it up here! (See the tooltip for an example) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STICK_HERE {
            get {
                return ResourceManager.GetString("STICK_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TextBox に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TEXT_BOX {
            get {
                return ResourceManager.GetString("TEXT_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   upper case letters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UPPER_CASE {
            get {
                return ResourceManager.GetString("UPPER_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use as is に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string USE_AS_IS {
            get {
                return ResourceManager.GetString("USE_AS_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ViewModel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VIEW_MODEL {
            get {
                return ResourceManager.GetString("VIEW_MODEL", resourceCulture);
            }
        }
    }
}
